name: dashboard-coordinator
region: nyc
services:
  - name: coord-api
    github:
      repo: Mister-Yo/dashboard
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: packages/coord-api/Dockerfile
    http_port: 8080
